fix: Correct config.toml file handling on Windows (#281)
## Motivation

Currently, whenever modifying the `config.toml` file on Windows using
`sloctl config` commands an error arises:

> Error: rename C:\Users\mh\.config\nobl9\config.toml3389036250
C:\Users\mh\.config\nobl9\config.toml: The process cannot access the
file because it is being used by another process.

The issue comes from Nobl9 SDK and is fixed by
https://github.com/nobl9/nobl9-go/pull/639.

## Related changes

- https://github.com/nobl9/nobl9-go/pull/639

## Testing

Tested on Windows 11 23H2 run inside Virtual Box.


![image](https://github.com/user-attachments/assets/81fa4790-3195-4be9-9925-e517f9bb80e0)

## Release Notes

`sloctl config` commands which modify _config.toml_ should now work on
Windows.