feat: [PC-14270] allow user to filter budget adjustment kind by slo name (#349)
## Motivation

We have `BudgetAdjustments` resources that can have multiple associated
SLOs, like this:

```yaml
apiVersion: n9/v1alpha
kind: BudgetAdjustment
metadata:
  displayName: Example Display Name
  name: test-2025-06-06-001
spec:
  description: Example description
  duration: 15m
  filters:
    slos:
      - name: slo-2025-06-01-001
        project: prometheus
      - name: slo-2025-06-01-002
        project: prometheus
      - name: slo-2025-06-01-003
        project: prometheus
```

We need a way to filter `BudgetAdjustments` by a specific SLO, which is
identified by its **project name** and **SLO name**.

## Summary

Add new filters for `sloctl` CLI tool command:

```
  -p, --project string   Filter resource by SLO Project name. Example: my-sample-project-name
      --slo string       Filter resource by SLO name. Example: my-sample-slo-name

```

✅ The two flags **must be used together or not at all**.

Values will be passed in requests **only for
`manifest.KindBudgetAdjustment`** with the following query keys (defined
in `nobl9-go`):

```go
QueryKeySLOName        = "slo"
QueryKeySLOProjectName = "slo_project"
```

## Testing

Running:

```bash
sloctl get budgetadjustments --slo slo-2025-06-01-003
```

Should produce:

```bash
Error: if any flags in the group [slo project] are set they must all be set; missing [project]
```

Running:

```bash
sloctl get budgetadjustments --project prometheus
```

Should produce:

```bash
Error: if any flags in the group [slo project] are set they must all be set; missing [slo]
```

A successful request should be made with **both flags provided
together**:

```bash
sloctl get budgetadjustments --slo slo-2025-06-01-003 --project prometheus
```

Or without specifying both flags:

```bash
sloctl get budgetadjustments
```

The new flags should be available **only for `sloctl get
budgetadjustments`** command.


## Release Notes

Added support for filtering BudgetAdjustments by SLO name and project in
sloctl. This lets you narrow down results to a specific SLO when
retrieving budget adjustments. The two flags --slo and --project must be
used together or not at all.

---------

Co-authored-by: Mateusz Hawrus <48822818+nieomylnieja@users.noreply.github.com>